//  Generated by Generamba
//
//  ProfileProfileRouter.swift
//  Wakeapper
//
//  Created by Sergey Borovikov on 07/10/2018.
//  Copyright © 2018 Company. All rights reserved.
//

import Foundation
import SwinjectStoryboard

protocol ProfileRouterI {
    func segueTo(from context: ProfileViewController)
}

final class ProfileRouter {}

extension ProfileRouter: ProfileRouterI {
    func segueTo(from context: ProfileViewController) {
        
    }
}
