//  Generated by Generamba
//
//  ProfileProfileFactory.swift
//  Wakeapper
//
//  Created by Sergey Borovikov on 07/10/2018.
//  Copyright © 2018 Company. All rights reserved.
//

import SwinjectStoryboard

extension SwinjectStoryboard {
    
    class func setupProfileFactory() {
        
        defaultContainer.register(ProfileRouterI.self) { _ in ProfileRouter() }
        
        defaultContainer.register(ProfileViewModelI.self) { resolver in ProfileViewModel() }
        
        defaultContainer.storyboardInitCompleted(ProfileViewController.self) { resolver, controller in
            controller.viewModel = resolver.resolve(ProfileViewModelI.self)
            controller.router = resolver.resolve(ProfileRouterI.self)
        }
    }
}
