//  Generated by Generamba
//
//  ProfileProfileViewModel.swift
//  Wakeapper
//
//  Created by Sergey Borovikov on 07/10/2018.
//  Copyright © 2018 Company. All rights reserved.
//

import Foundation
import RxCocoa
import RxSwift

protocol ProfileViewModelI {
    // Input

    // Output

}

final class ProfileViewModel {



    init() {

    }
}

extension ProfileViewModel: ProfileViewModelI {

    
}
