//  Generated by Generamba
//
//  SettingsSettingsFactory.swift
//  Wakeapper
//
//  Created by Sergey Borovikov on 07/10/2018.
//  Copyright © 2018 Company. All rights reserved.
//

import SwinjectStoryboard

extension SwinjectStoryboard {
    
    class func setupSettingsFactory() {
        
        defaultContainer.register(SettingsRouterI.self) { _ in SettingsRouter() }
        
        defaultContainer.register(SettingsViewModelI.self) { resolver in SettingsViewModel() }
        
        defaultContainer.storyboardInitCompleted(SettingsViewController.self) { resolver, controller in
            controller.viewModel = resolver.resolve(SettingsViewModelI.self)
            controller.router = resolver.resolve(SettingsRouterI.self)
        }
    }
}
