//  Generated by Generamba
//
//  SettingsSettingsViewModel.swift
//  Wakeapper
//
//  Created by Sergey Borovikov on 07/10/2018.
//  Copyright © 2018 Company. All rights reserved.
//

import Foundation
import RxCocoa
import RxSwift

protocol SettingsViewModelI {
    // Input

    // Output

}

final class SettingsViewModel {



    init() {

    }
}

extension SettingsViewModel: SettingsViewModelI {

    
}
