//  Generated by Generamba
//
//  SettingsSettingsRouter.swift
//  Wakeapper
//
//  Created by Sergey Borovikov on 07/10/2018.
//  Copyright © 2018 Company. All rights reserved.
//

import Foundation
import SwinjectStoryboard

protocol SettingsRouterI {
    func segueTo(from context: SettingsViewController)
}

final class SettingsRouter {}

extension SettingsRouter: SettingsRouterI {
    func segueTo(from context: SettingsViewController) {
        
    }
}
