//  Generated by Generamba
//
//  MainScreenMainScreenViewModel.swift
//  Wakeapper
//
//  Created by Sergey Borovikov on 30/09/2018.
//  Copyright © 2018 Company. All rights reserved.
//

import Foundation
import RxCocoa
import RxSwift

protocol MainScreenViewModelI {
    
    // Input
    func onButton()
    
    // Output
    var wakeupDetectorType: Observable<WakeupDetectorType> { get }
    var moveDetection: Observable<Void> { get }
    var bigTimerObservable: Observable<Int> { get }
}

final class MainScreenViewModel {

    private let _wakeUpDetectorService: WakeupDetectorServiceI!
    
    init(wakeUpDetectorService: WakeupDetectorServiceI) {
        _wakeUpDetectorService = wakeUpDetectorService
    }
}

extension MainScreenViewModel: MainScreenViewModelI {

    func onButton() {
        _wakeUpDetectorService?.startWakupDetection()
    }

    var wakeupDetectorType: Observable<WakeupDetectorType> { return _wakeUpDetectorService.wakeupDetectorType }
    var moveDetection: Observable<Void> { return _wakeUpDetectorService.moveDetection }
    var bigTimerObservable: Observable<Int> { return _wakeUpDetectorService.bigTimerObservable }
}
