//  Generated by Generamba
//
//  MainScreenMainScreenRouter.swift
//  Wakeapper
//
//  Created by Sergey Borovikov on 30/09/2018.
//  Copyright © 2018 Company. All rights reserved.
//

import Foundation
import SwinjectStoryboard

protocol MainScreenRouterI {
    func segueTo(from context: MainScreenViewController)
}

final class MainScreenRouter {}

extension MainScreenRouter: MainScreenRouterI {
    func segueTo(from context: MainScreenViewController) {
        
    }
}
