//  Generated by Generamba
//
//  StartStartRouter.swift
//  Wakeapper
//
//  Created by Sergey Borovikov on 30/09/2018.
//  Copyright © 2018 Company. All rights reserved.
//

import Foundation
import SwinjectStoryboard

protocol StartRouterI {
    func segueToMain(from context: StartViewController)
}

final class StartRouter {}

extension StartRouter: StartRouterI {
    func segueToMain(from context: StartViewController) {
        let mainViewController = SwinjectStoryboard.create(name: "MainScreen", bundle: nil)
        .instantiateViewController(withIdentifier: "MainScreenViewController")
        context.navigationController?.pushViewController(mainViewController, animated: true)
    }
}
