//  Generated by Generamba
//
//  StartStartViewModel.swift
//  Wakeapper
//
//  Created by Sergey Borovikov on 30/09/2018.
//  Copyright © 2018 Company. All rights reserved.
//

import Foundation
import RxCocoa
import RxSwift

protocol StartViewModelI {
    
    
}

final class StartViewModel {
    
}

extension StartViewModel: StartViewModelI {
    
}
