//  Generated by Generamba
//
//  StartStartViewController.swift
//  Wakeapper
//
//  Created by Sergey Borovikov on 30/09/2018.
//  Copyright © 2018 Company. All rights reserved.
//

import UIKit
import RxSwift

class StartViewController: UIViewController {
    
    var router: StartRouterI!
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        router.segueToMain(from: self)
    }
}
