//  Generated by Generamba
//
//  AlarmsAlarmsRouter.swift
//  Wakeapper
//
//  Created by Sergey Borovikov on 07/10/2018.
//  Copyright © 2018 Company. All rights reserved.
//

import Foundation
import SwinjectStoryboard

protocol AlarmsRouterI {
    func segueTo(from context: AlarmsViewController)
}

final class AlarmsRouter {}

extension AlarmsRouter: AlarmsRouterI {
    func segueTo(from context: AlarmsViewController) {
        
    }
}
