//  Generated by Generamba
//
//  AlarmsAlarmsViewModel.swift
//  Wakeapper
//
//  Created by Sergey Borovikov on 07/10/2018.
//  Copyright © 2018 Company. All rights reserved.
//

import Foundation
import RxCocoa
import RxSwift

protocol AlarmsViewModelI {
    // Input

    // Output

}

final class AlarmsViewModel {



    init() {

    }
}

extension AlarmsViewModel: AlarmsViewModelI {

    
}
