//  Generated by Generamba
//
//  AlarmsAlarmsFactory.swift
//  Wakeapper
//
//  Created by Sergey Borovikov on 07/10/2018.
//  Copyright © 2018 Company. All rights reserved.
//

import SwinjectStoryboard

extension SwinjectStoryboard {
    
    class func setupAlarmsFactory() {
        
        defaultContainer.register(AlarmsRouterI.self) { _ in AlarmsRouter() }
        
        defaultContainer.register(AlarmsViewModelI.self) { resolver in AlarmsViewModel() }
        
        defaultContainer.storyboardInitCompleted(AlarmsViewController.self) { resolver, controller in
            controller.viewModel = resolver.resolve(AlarmsViewModelI.self)
            controller.router = resolver.resolve(AlarmsRouterI.self)
        }
    }
}
